### ISSUE TITLE
cliendid kan niet hergebruikt worden

### ISSUE THREAD

**Issue by TimGrootscholten** [TimGrootscholten/Tournaments-Server#2]
The instance of entity type 'Token' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

**Comment by Davement** [comment]
Je kan ook inloggen zonder clientid. DIt is ook niet de bedoeling.

**Comment by Davement** [comment]
Als je client id al bestaat en probeert nog een keer in te loggen via de authenticate gooit hij je token gegevens uit de database. Dit doet hij omdat er dan iets niet klopt. Want er zou ingelogd moeten worden via de refresh token en die moet dan overeen komen met de gene uit de database.
De error is gefixed nu gooien we een eigen error terug deze moet nog wel afgevangen worden.

**Comment by Davement** [comment]
De volgende punten moeten nog opgepakt worden in dit ticket:

- ClientId generen op de front end en opslaan in de localhost.
- De error aanpassen naar een logische error. Nu gooit hij een 500 internal server error.
- Die error afvangen op de frontend en dan vervolgens automatisch uitloggen.

**Comment by Davement** [comment]
De error aanpassen naar een logische error. Nu gooit hij een 500 internal server error. Deze wordt gefixed in #4

**Comment by Davement** [comment]
- [ ] Die error afvangen op de frontend en dan vervolgens automatisch uitloggen.
